config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  mount ActionCable.server => '/cable'
  devise_for :users
  resources :posts do
    resources :comments, except: %i[show]
  end
  resources :users, except: %i[create new] do
    resources :ratings, only: %i[create destroy index]
  end
  resources :tags, only: %i[show create]
  resources :favorites, only: %i[index create destroy]
end

app/models/favorite.rb
# frozen_string_literal: true

class Favorite < ApplicationRecord
  belongs_to :post
  belongs_to :user
end

app/controllers/favorites_controller.rb
# frozen_string_literal: true

class FavoritesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_post, except: :index

  def index
    @favorites = current_user.favorite_posts
    @favorites.each { |fav| truncate_body(fav) }
    render json: @favorites
  end

  def create
    fav = Favorite.where(user: current_user, post: @post)
    Favorite.create(post: @post, user: current_user) if fav.blank?
    truncate_body(@post)
    render json: @post
  end

  def destroy
    Favorite.where(post: @post, user: current_user).first.destroy
    render json: @post
  end

  private

  def truncate_body(post)
    post.body = post.body.truncate(40, separator: ' ')
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/favorites_helper.rb
# frozen_string_literal: true

module FavoritesHelper
end

app/views/favorites/_links.html.slim
- if user_signed_in?
  .favorite-link
    - if post.favorites.find_by(user: current_user).blank?
      = link_to "Add to favorites", favorites_path(id: post.id), method: :post, remote: true, class: "btn btn-primary add"
    - else
      = link_to "Remove from favorites", favorite_path(post), method: :delete, remote: true, class: "btn btn-primary remove"