config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'posts#index'
  mount ActionCable.server => '/cable'
  devise_for :users
  resources :posts do
    resources :comments, except: %i[show]
  end
  resources :users, except: %i[create new] do
    resources :ratings, only: %i[create destroy index]
  end
  resources :tags, only: %i[show create]
  resources :favorites, only: %i[index create destroy]
end

app/models/post.rb
# frozen_string_literal: true

class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  include PgSearch
  pg_search_scope :search_scope, against: %i[title body adress],
                                 associated_against: { user: :username,
                                                       tags: :name,
                                                       comments: :body }

  validates :body, presence: true, length: { maximum: 2000 }
  validates :title, presence: true, length: { maximum: 100 }
  validates :adress, length: { maximum: 100 }

  belongs_to :user
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  enum status: %i[active inactive]

  def current_tags
    tags.map(&:name).map { |t| t + ',' }.join
  end

  def current_tags=(values)
    self.tags = values.split(',').map { |t| Tag.find_by(name: t) }
  end

  def self.search(keywords)
    keywords.present? ? search_scope(keywords) : all.order('created_at DESC')
  end
end

app/controllers/posts_controller.rb
# frozen_string_literal: true

class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  before_action :check_owner, only: %i[destroy edit update]

  def index
    @posts = Post.search(params[:keywords]).uniq
  end

  def show; end

  def edit; end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    # link the post to user that logged in atm
    @post.user = current_user
    if @post.save
      # redirect to created post and show flash
      redirect_to @post, success: 'Post successfully created !'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      # redirect to updated post and show flash
      redirect_to @post, success: 'Post successfully updated !'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    # redirect to root and show flash
    redirect_to posts_path, success: 'Post successfully deleted !'
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, :image, :image_cache, :status,
                                 :adress, :current_tags)
  end

  def check_owner
    # check if current user is owner of the post
    redirect_to @post, alert: 'You are not the owner of this post' unless
    current_user == @post.user || current_user.admin?
  end
end

app/helpers/posts_helper.rb
# frozen_string_literal: true

module PostsHelper
end

app/views/posts/_form.html.slim
= form_for @post, data: {init: :images} do |f|
  = render "shared/errors", object: @post
  - if !@post.new_record?
    .form-group
      = f.select :status, Post.statuses.keys
  .form-group
    = image_tag(@post.image.url(:post_thumb), class: "img-thumbnail load-img")
    = f.file_field :image, class: "form-control-file input-img"
    = f.hidden_field :image_cache
  .form-group
    = f.label :title
    = f.text_field :title, class: "form-control"
  .form-group
    = f.label :adress
    = f.text_field :adress, class: "form-control"
  .tags-container data-init="tags"
    ul.tag-errors
    span tag can not contain spaces or commas
    .inputs
      = text_field_tag "tag-field"
      = link_to "Create new tag", "" ,  class:"btn btn-outline-primary", id: "tag-link"
    = f.hidden_field :current_tags
    .dropdown
      button#dropdownMenu2.btn.btn-default.dropdown-toggle.all-tags aria-expanded="false" aria-haspopup="true" data-toggle="dropdown" type="button"
        | Select tags
      ul.dropdown-menu.all-tags.pre-scrollable aria-labelledby="dropdownMenu2"
        - Tag.all.map(&:name).map do |t|
          li.tag
            input type="checkbox" value=t /
            label= t
    .current-tags
      = render "tags/tags", tags: @post.current_tags.split(",")
  .form-group
    = f.label :body
    = f.text_area :body, class: "form-control", rows: "10"
  .form-group
    = f.submit "Save", class: "btn btn-outline-primary"
    = link_to "Back", :back, class: "btn btn-outline-secondary"

app/views/posts/_post.html.slim
article.post-preview
  section.post-head
    div class="favorite-link-container-#{post.id}"
      = render "favorites/links", post: post
    h2= link_to post.title, post_path(post)
    small
      span Posted by
      =>< link_to post.user.username, user_path(post.user)
      time= post.created_at.to_date
  section.post-body.clearfix
    = image_tag(post.image.url(:post_thumb), class: "img-thumbnail thumb")
    p= truncate(post.body, length: 160, separator: ' ')
  section.tags
    = raw post.tags.map(&:name).map{ |t| link_to t, tag_path(t), class: "badge badge-pill badge-primary" }.join

app/views/posts/edit.html.slim
h1 Edit post
= render "form"

app/views/posts/index.html.slim
h1 All Posts
= render @posts

app/views/posts/new.html.slim
h1 New Post
= render "form"

app/views/posts/show.html.slim
article.post-show data-init="comments" data-post-id="#{@post.id}"
  section.post-head
    h1= @post.title
    div class="favorite-link-container-#{@post.id}"
      = render 'favorites/links', post: @post
    .post-info
      .info-top
        span Posted by
        = link_to @post.user.username, user_path(@post.user)
        time= @post.created_at.to_date
        - if access?(@post.user)
          strong.links
            => link_to "Edit", edit_post_path(@post)
            |
            = link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure ?"}
      .info-bottom
        h3
          | Adress:
          span= @post.adress
        h3
          | Status:
          span= @post.status
        .tags
          = render "tags/tags", tags: @post.tags.map(&:name)
  section.post-body
    = image_tag(@post.image.url(:post), class: "image-show")
    p= @post.body
.comments
  .comments-form
  .new-comment-btn
    = link_to "New Comment", new_post_comment_path(@post), remote: true, class: "btn btn-outline-primary" if user_signed_in?
  .comments-content